name: Node.js Package

on:
     push:
          branches:
               - main

jobs:
     publish-gpr:
          environment: NPM

          runs-on: ubuntu-latest
          permissions:
               contents: read
               packages: write
          steps:
               - name: Checkout repository
                 uses: actions/checkout@v4

               - name: Setup Node.js
                 uses: actions/setup-node@v4
                 with:
                      node-version: 20

               - name: Install pnpm
                 run: npm install -g pnpm

               - name: Install dependencies
                 run: pnpm install --frozen-lockfile

               # Publish github package
               - name: Publish github package
                 run: |
                      pnpm config set '//npm.pkg.github.com/@AzPepoze/:_authToken' "${{secrets.GITHUB_TOKEN}}"
                      pnpm publish --no-git-checks --access public

               # Publish to npm Registry
               - name: Publish to npm Registry
                 run: |
                      pnpm config set '//registry.npmjs.org/:_authToken' "${{secrets.NPM_TOKEN}}"
                      pnpm publish --access public
